/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBException;
import objects.Table;

/**
 *
 * @author Amr Ashraf
 */
public class ClientGui2 extends javax.swing.JFrame {

    
    List<Table> alltables ;
     String clientname=null;
     String order = " ";
    int indix;
    
    ArrayList<String>mainDish = new ArrayList<>();
    ArrayList<String>appetizerDish = new ArrayList<>();
    ArrayList<String>desertDish = new ArrayList<>();
    
//    ArrayList<String>order = new ArrayList<>();
    
   
    /**
     * Creates new form ClientGui2
     */
    public ClientGui2(List<Table> x , String y ,int i) {
        initComponents();
        alltables = x;
       clientname = y;
        indix=i;
    }

    private ClientGui2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainCB = new javax.swing.JComboBox<>();
        desertCB = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MN = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        appN = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        appetizerCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        desN = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("choose Main dish :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 59));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Choose  appetizer :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 59));

        mainCB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mainCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grilled Chicken", "Mushroom Soup", "Beef Steak" }));
        jPanel1.add(mainCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 130, 200, -1));

        desertCB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        desertCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple Pie", "Molten Cake" }));
        jPanel1.add(desertCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 193, 30));

        jButton7.setBackground(new java.awt.Color(201, 29, 29));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Show Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 150, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Number of plates :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, 59));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Add");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 40, 30));

        MN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        MN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", " " }));
        jPanel1.add(MN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 60, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/dinner.png"))); // NOI18N
        jButton6.setText("Reserve another table");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 310, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Number of plates :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, 59));

        appN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        appN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", " " }));
        jPanel1.add(appN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 60, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Choose  desert :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 59));

        appetizerCB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        appetizerCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Greek Salade", "Fried Potatos" }));
        appetizerCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appetizerCBActionPerformed(evt);
            }
        });
        jPanel1.add(appetizerCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 193, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 40, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/add.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 40, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/add.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 40, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Number of plates :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, 59));

        desN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        desN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", " " }));
        jPanel1.add(desN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 60, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/save.png"))); // NOI18N
        jButton4.setText("reserve and Take  Receipt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 300, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Add");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Add");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/exit.png"))); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 150, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/WGPMifw.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-830, -60, 1700, 600));

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appetizerCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appetizerCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appetizerCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(mainCB.getSelectedIndex()==0){
             mainDish.add("Grilled Chicken");
             order+=" Grilled Chicken (Number of plates=";
        }
           
        else if(mainCB.getSelectedIndex()==1){
            mainDish.add("Mushroom Soup");
            order+=" Mushroom Soup  (Number of plates=";
        }
             
        else if(mainCB.getSelectedIndex()==2){
            mainDish.add("Beef Steak");
            order+=" Beef Steak  (Number of plates=";
        }
            
        
        mainDish.add(Integer.toString(MN.getSelectedIndex()+1));
         order+=Integer.toString(MN.getSelectedIndex()+1);
         order+=") ,";
        
        
        
    JOptionPane.showMessageDialog(rootPane, "Your Order is added, once you press reserve it will be saved");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (appetizerCB.getSelectedIndex()==0){
            appetizerDish.add("Greek Salade");
            order+=" Greek Salade (Number of plates=";
        }
           
        if (appetizerCB.getSelectedIndex()==1){
            appetizerDish.add("Fried Potatos");
            order+=" Fried Potatos (Number of plates=";
        }
            
        
        appetizerDish.add(Integer.toString(appN.getSelectedIndex()+1));
        order+=Integer.toString(appN.getSelectedIndex()+1);
        order+=") ,";
        
         JOptionPane.showMessageDialog(rootPane, "Your Order is added, once you press reserve it will be saved");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if (desertCB.getSelectedIndex()==0){
             desertDish.add("Apple Pie");
             order+=" Apple Pie (Number of plates=";
        }
           
        if (desertCB.getSelectedIndex()==1){
            desertDish.add("Molten Cake");
            order+=" Molten Cake (Number of plates=";
        }
            
        
        desertDish.add(Integer.toString(desN.getSelectedIndex()+1));
        order+=Integer.toString(desN.getSelectedIndex()+1);
        order+=") ,";
        
         JOptionPane.showMessageDialog(rootPane, "Your Order is added, once you press reserve it will be saved");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(mainDish.size()==0 &&appetizerDish.size()==0 && desertDish.size()==0)
            JOptionPane.showMessageDialog(rootPane, "You must choose at least one of the meals");
        else
        {
         ClientGui3  m=null;
        try {
            m = new ClientGui3(alltables,clientname,indix,mainDish,appetizerDish,desertDish,order);
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui2.class.getName()).log(Level.SEVERE, null, ex);
        }
                    m.setVisible(true);
                     dispose();
        }               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Login l=null;
        try {
            l = new Login();
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        ClientGui1 l=null;
        try {
            l = new ClientGui1(alltables, clientname,0);
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        
        menu menu = new menu();
        menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MN;
    private javax.swing.JComboBox<String> appN;
    private javax.swing.JComboBox<String> appetizerCB;
    private javax.swing.JComboBox<String> desN;
    private javax.swing.JComboBox<String> desertCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mainCB;
    // End of variables declaration//GEN-END:variables
}
