/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import XmlRead.RestaurantXml;
import XmlRead.UserXml;
import XmlWrite.Reservations;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

/**
 *
 * @author Amr Ashraf
 */
public class DeleteUser extends javax.swing.JFrame {

    /**
     * Creates new form DeleteEmployeeOrUser
     */
    public DeleteUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter The  Name : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter The Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 206, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 206, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-remove-100.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 70, 80));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-back-64.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 150, 70));

        jLabel3.setText("you should enter the name and username with capital and small letter as written in user's data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, -1, 50));

        jLabel5.setText("you can also remove a client account");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("once the account is deleted you cannot recover it again");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/web-fired-any-reason-no-reason-tzr-780x501.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JAXBContext jax=null;
        try {
            jax = JAXBContext.newInstance(RestaurantXml.class);
        } catch (JAXBException ex) {
            Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        Unmarshaller unm=null;
        try {
            unm = jax.createUnmarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
        }
         RestaurantXml r=null;
        try {
            r = (RestaurantXml) unm.unmarshal(new File ("Restaurant.xml"));
        } catch (JAXBException ex) {
            Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
         List<UserXml> usList = r.getUsers().getUserList();
         
         
         List<UserXml> uxml=new ArrayList<>();
         
         int check=0;
         
        for (UserXml x :usList) {
                if(x.getName().equals(jTextField1.getText()) && x.getUsername().equals(jTextField2.getText()))
                {
                    if(x.getRole().equals("Manager")){
                    check = -1;
                    UserXml y = new UserXml();
                    y=x;
                    uxml.add(y);
                    }
                    else 
                   {
                    check++; 
                   }
                }
            
                else
            {
               UserXml y = new UserXml();
               y=x;
               uxml.add(y);
                
            }

        }
        if(check==0)
            JOptionPane.showMessageDialog(rootPane, "There is no user on the system with the same name and username");
        else if(check == -1)
        JOptionPane.showMessageDialog(rootPane, "name and username entered refers to a manager, you dont have the right to remove a manager you should contact the HEAD MANAGER");    
        else
        {
            r.getUsers().setUserList(uxml);
                    JAXBContext jax2=null;
        try {
            jax2 = JAXBContext.newInstance(RestaurantXml.class); 
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        Marshaller mm=null;
        try {
            mm = jax2.createMarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            mm.marshal(r,new File("Restaurant.xml"));
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           Managergui m=null;
             try {
                 m = new Managergui();
             } catch (JAXBException ex) {
                 Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
             }
           m.setVisible(true);
           dispose();
            JOptionPane.showMessageDialog(rootPane, "The User Deleted Successfully");
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Managergui m=null;
             try {
                 m = new Managergui();
             } catch (JAXBException ex) {
                 Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
             }
           m.setVisible(true);
           dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
