/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import UsersByInheritance.Client;
import UsersByInheritance.Cooker;
import UsersByInheritance.Manager;
import UsersByInheritance.User;
import UsersByInheritance.Waiter;
import XmlRead.RestaurantXml;
import XmlRead.TableXml;
import XmlRead.UserXml;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import objects.Table;

/**
 *
 * @author Amr Ashraf
 */
public class Login extends javax.swing.JFrame {
List<User> allusers = new ArrayList<>();
List<Table> alltables = new ArrayList<>();
String name=null;

    /**
     * Creates new form LoginSC
     */
    public Login() throws JAXBException {
        initComponents();
        readFromXml();
    }
    
    public void readFromXml() throws JAXBException
    {
        JAXBContext jax = JAXBContext.newInstance(RestaurantXml.class);
        Unmarshaller unm= jax.createUnmarshaller();
         RestaurantXml r = (RestaurantXml) unm.unmarshal(new File ("Restaurant.xml"));
         
         List<TableXml> Tlist = r.getTables().getTableList();
         List<UserXml> usList = r.getUsers().getUserList();
         
         
         
         
         
         
        for (UserXml x :usList) {
                if(x.getRole().equals("Manager"))
            {
                Manager m = new Manager(x.getName(), x.getUsername(), x.getPassword());
                allusers.add(m);
            }
            else if(x.getRole().equals("Client"))
            {
                Client m = new Client(x.getName(), x.getUsername(), x.getPassword());
                allusers.add(m);
            }
              else if(x.getRole().equals("Waiter"))
            {
                Waiter m = new Waiter(x.getName(), x.getUsername(), x.getPassword());
                allusers.add(m);
            }
            
             else if(x.getRole().equals("Cooker"))
            {
                Cooker m = new Cooker(x.getName(), x.getUsername(), x.getPassword());
                allusers.add(m);
            }
            
        }
        
        for (TableXml tableXml : Tlist) {
            Table t = new Table(tableXml.getNumber(),tableXml.getNumberOfSeats(),tableXml.isSmoking());
            alltables.add(t);
        }
    }
    
     public void delete ()
    {
        jTextField1.setText(null);
        jPasswordField1.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 54, 90, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("password  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 90, 37));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 262, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 262, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-login-64.png"))); // NOI18N
        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-add-user-male-40.png"))); // NOI18N
        jButton2.setText("Create new user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/exit.png"))); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/couple-romantic-date-dinner-man-holding-woman-hand-sitting-served-table-dark-room-window-with-view-moon-night_33099-2521.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().isEmpty() || jPasswordField1.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(rootPane, "Please Enter All Fields");
        }
        else{
           
        String UN=jTextField1.getText();
        String UP=jPasswordField1.getText();
        
        User LN = null;
        
        for (User x : allusers) {
            if(x.getUsername().equals(UN) && x.getPassword().equals(UP))
            {
                LN=x;
                name = x.getName();
                break;
            }
        }
        
        
             if(LN==null)
        {
              JOptionPane.showMessageDialog(rootPane, "Invalid");
            delete();
        }
             
             else
    {
                 if(LN instanceof Manager)
        {
                  Managergui m;
                     try {
                         m = new Managergui ();
                         m.setVisible(true);
                     } catch (JAXBException ex) {
                         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     dispose();
                     JOptionPane.showMessageDialog(rootPane, "Welcome Mr "+name);
                   
        }
                  else if(LN instanceof Client)
        {
                  ClientGui1 m=null;
                     try {
                         m = new ClientGui1(alltables,name,0);
                     } catch (JAXBException ex) {
                         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    m.setVisible(true);
                    dispose();
                     JOptionPane.showMessageDialog(rootPane, "Welcome Mr "+name);
        } 
          else if(LN instanceof Waiter)     
        {
            Waitergui m=null;
                     try {
                         m = new Waitergui(alltables); //hena el mafrod fe all dishes w el client bta3 kol table wel table reserved walla la
                     } catch (JAXBException ex) {
                         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                     }
            m.setVisible(true); 
            dispose();
            JOptionPane.showMessageDialog(rootPane, "Welcome "+name);
        }
          else
          {
              Cookergui m;
                     try {
                         m = new Cookergui(alltables);
                         m.setVisible(true);
                     } catch (JAXBException ex) {
                         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                     }
                
              dispose();
              JOptionPane.showMessageDialog(rootPane, "Welcome "+name);
              JOptionPane.showMessageDialog(rootPane, "move with the cursor if the order is too long");
          }
    }
    
            
        }    
       
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Newaccount n = new Newaccount(allusers);
        n.setVisible(true);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (JAXBException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
