/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import UsersByInheritance.User;
import XmlRead.RestaurantXml;
import XmlRead.UserXml;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import objects.Table;

/**
 *
 * @author kamal alexander
 */
public class Newemployee extends javax.swing.JFrame {

    
    List<User> allusers = new ArrayList<>();
    List<Table> alltables;
    /**
     * Creates new form Newaccount
     */
    public Newemployee(List<User> allusers,List<Table> alltables) {
        initComponents();
        this.allusers=allusers;
        this.alltables = alltables;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 160, 35));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 160, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 14));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("confirm password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 160, 36));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 35));

        jPanel1.setBackground(new java.awt.Color(152, 152, 152));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 70, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "waiter", "cooker" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 20, 160, -1));

        jLabel6.setText("to add a new manager contact the HEAD MANAGER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 300, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/online-reserved-table-vector-illustration_103044-523.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 620, 570));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int check=0;
       
       if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() ||jPasswordField1.getText().isEmpty() || jPasswordField2.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(rootPane, "Please enter all fields ");
           dispose();
           Newemployee l = new Newemployee(allusers,alltables);
           l.setVisible(true);
       }
       else
       {
        for (User x : allusers) {
            if(x.getUsername().equals(jTextField2.getText())){
                check++;
                break;
            }
        }
        if(check>0){
            
           JOptionPane.showMessageDialog(rootPane, "username already exist, try another one");
           dispose();
           Newemployee l = new Newemployee(allusers,alltables);
           l.setVisible(true);
        }
        else if(jPasswordField1.getText().length()<6)
        {
            JOptionPane.showMessageDialog(rootPane, "employee should have password contains at least 6 digit or character!");
           dispose();
           Newemployee l = new Newemployee(allusers,alltables);
           l.setVisible(true);
        }
        else if(jPasswordField1.getText().equals(jPasswordField2.getText()))
        {
        JAXBContext jax;
        try {
            jax = JAXBContext.newInstance(RestaurantXml.class);
            Unmarshaller unm= jax.createUnmarshaller();
            RestaurantXml r = (RestaurantXml) unm.unmarshal(new File ("Restaurant.xml"));
            UserXml u=new UserXml();
            u.setName(jTextField1.getText());
            u.setUsername(jTextField2.getText());
            u.setPassword(jPasswordField1.getText());
            if(jComboBox1.getSelectedIndex()==0)
            u.setRole("Waiter");
            else
            u.setRole("Cooker");    
            r.getUsers().getUserList().add(u);
            jax = JAXBContext.newInstance(RestaurantXml.class);
            Marshaller nunm= jax.createMarshaller();
            nunm.marshal(r, new File ("Restaurant.xml"));
            } catch (JAXBException ex) {
            Logger.getLogger(Newemployee.class.getName()).log(Level.SEVERE, null, ex);
            
        }
         Managergui l=null;
        try {
            l = new Managergui();
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "You have added new employee succefully");
        dispose();
       }
        else 
        {
           JOptionPane.showMessageDialog(rootPane, "password dont match");
           dispose();
           Newemployee l = new Newemployee(allusers,alltables);
           l.setVisible(true);
       } }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Managergui l;
        try {
            l = new Managergui();
            l.setVisible(true);
        } catch (JAXBException ex) {
            Logger.getLogger(Newemployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
