/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Rating.Rating;
import Rating.Ratings;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

/**
 *
 * @author Amr Ashraf
 */
public class RatingGui extends javax.swing.JFrame {
    
    String name=null;
    int number;
    /**
     * Creates new form RatingGui
     */
    public RatingGui(String name , int number) {
        initComponents();
        this.name=name;
        this.number=number;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Rate The Food From 0 to 10 :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rate The Waiter From 0 to 10 :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 49));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rate The Service From 0 to 10 :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 49));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox1.setSelectedIndex(10);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox2.setSelectedIndex(10);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox3.setSelectedIndex(10);
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-submit-resume-40.png"))); // NOI18N
        jButton1.setText("Submit and Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 206, 55));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/exit.png"))); // NOI18N
        jButton2.setText("logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 127, 55));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Put Comment :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 110, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 242, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/96985158-stock-vector-hands-in-business-suit-holding-embracing-red-heart-symbol-with-text-we-care-vector-cartoon-illustrat.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isEmpty())
        {
         JOptionPane.showMessageDialog(rootPane,"Please Put a comment");
        }
        else
        {
        Ratings r = new Ratings();
        JAXBContext jax=null;
        try {
            jax = JAXBContext.newInstance(Ratings.class);
        } catch (JAXBException ex) {
            Logger.getLogger(RatingGui.class.getName()).log(Level.SEVERE, null, ex);
        }
      Unmarshaller unm=null;               
        try {
            unm = jax.createUnmarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(RatingGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
             r = (Ratings) unm.unmarshal(new File ("Rating.xml"));
        } catch (JAXBException ex) {
            Logger.getLogger(RatingGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        Ratings s=  r;
        Rating t2=new Rating();
        t2.setClient(name);
        t2.setTablenumber(number);
        t2.setFoodrate(jComboBox1.getSelectedIndex());
        t2.setWaiterrate(jComboBox2.getSelectedIndex());
        t2.setServicerate(jComboBox3.getSelectedIndex());
        t2.setComment(jTextField1.getText());
        
        
        s.getRatinglist().add(t2);
        
        
        JAXBContext jax5=null;
        try {
            jax5 = JAXBContext.newInstance(Ratings.class);
        } catch (JAXBException ex) {
            Logger.getLogger(RatingGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        Marshaller mmm=null;
        try {
            mmm = jax5.createMarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(RatingGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            mmm.marshal(s,new File("Rating.xml"));
        } catch (JAXBException ex) {
            Logger.getLogger(RatingGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        Login l=null;
        try {
            l = new Login();
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        dispose();
         JOptionPane.showMessageDialog(rootPane, "Thank You For Rating Us");
         JOptionPane.showMessageDialog(rootPane, "we hope you enjoyed our service ");
     }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login l=null;
        try {
            l = new Login();
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        dispose();
         JOptionPane.showMessageDialog(rootPane, "we hope you enjoyed our service ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
