/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Rating.Rating;
import Rating.Ratings;
import XmlWrite.Reservations;
import XmlWrite.TableXmlWrite;
import XmlWrite.TablesXmlWrite;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

/**
 *
 * @author Amr Ashraf
 */
public class StartNewDay extends javax.swing.JFrame {

    /**
     * Creates new form StartNewDay
     */
    public StartNewDay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Are You Sure That You Want To Start New Day ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("  (Note : all data saved today will be deleted)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 43));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-back-arrow-64.png"))); // NOI18N
        jButton2.setText("Leave");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-gear-64.png"))); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/calendar_459-173.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           Reservations r=new Reservations();
         TableXmlWrite t2=new TableXmlWrite();
        t2.setName("000");
        t2.setNumber(0);
        t2.setOrder("0000");
        t2.setPaid(000);  

        List<TableXmlWrite> l =new ArrayList<>();
        
        TablesXmlWrite te =new TablesXmlWrite();
        te.setTableList(l);
        r.setTables(te);
        r.getTables().getTableList().add(t2);
     
       
               JAXBContext jax2=null;
        try {
            jax2 = JAXBContext.newInstance(Reservations.class); 
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        Marshaller mm=null;
        try {
            mm = jax2.createMarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            mm.marshal(r,new File("Reservation.xml"));
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        Rating ra = new Rating();
        Ratings ras=new Ratings();
        ra.setClient("00");
        ra.setFoodrate(0);
        ra.setServicerate(0);
        ra.setTablenumber(0);
        ra.setWaiterrate(0);
        ra.setComment("00");
        
        List<Rating> rlist = new ArrayList<Rating>();
        ras.setRatinglist(rlist);
        ras.getRatinglist().add(ra);
        
        
        JAXBContext gax=null;
        try {
            gax = JAXBContext.newInstance(Ratings.class);
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        Marshaller ma=null;
        try {
            ma = gax.createMarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ma.marshal(ras,new File("Rating.xml"));
        } catch (JAXBException ex) {
            Logger.getLogger(StartNewDay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         Login ll=null;
        try {
            ll = new Login();
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        ll.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(rootPane, "All Data Deleted succefully ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Login ll=null;
        try {
            ll = new Login();
        } catch (JAXBException ex) {
            Logger.getLogger(ClientGui3.class.getName()).log(Level.SEVERE, null, ex);
        }
        ll.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(rootPane, "All Data Protected succefully ");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
